on: push

jobs:
  esp32-platformio:
    container: infinitecoding/platformio-for-ci:latest
    runs-on: ubuntu-18.04
    steps:
      - run: |
          rm -fdr bin
          mkdir bin
        name: 'Prepare output directories'      
      - run: platformio ci --build-dir="./bin" --keep-build-dir --project-conf=platformio.ini ./src/
        name: 'Build firmware'
      - uses: actions/upload-artifact@v2
        with:
          name: firmware.bin
          path: bin/.pio/build/nodemcuv2/firmware.bin