on: push

jobs:
  esp32-platformio:
    container: infinitecoding/platformio-for-ci:latest
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: ls -l
      - run: |
          rm -fdr bin
          mkdir bin
        name: 'Prepare output directories'      
      - shell: bash
        env:
          WIFI_SSID: ${{ secrets.WIFI_SSID }}
          WIFI_PASSWORD: ${{ secrets.WIFI_PASSWORD }}
        run: |
          echo 'const char* ssid = "'${WIFI_SSID}'";' > src/credentials.h
          echo 'const char* password = "'${WIFI_PASSWORD}'";' >> src/credentials.h
      - run: platformio ci --build-dir="./bin" --keep-build-dir --project-conf=platformio.ini ./src/
        name: 'Build firmware'
      - uses: actions/upload-artifact@v2
        with:
          name: firmware.bin
          path: bin/.pio/build/nodemcuv2/firmware.bin