trigger:
- master

resources:
  containers:
  - container: platformio
    image: infinitecoding/platformio-for-ci:latest
    endpoint: dockerhub-infinite-coding

jobs:
  esp32-platformio:
    container: platformio
    runs-on: ubuntu-18.04
    steps:
      - run: |
          rm -fdr bin
          mkdir bin
        displayName: 'Prepare output directories'      
      - run: platformio ci --build-dir="./bin" --keep-build-dir --project-conf=platformio.ini ./src/
        displayName: 'Build firmware'
      - task: CopyFiles@2
        inputs:
          SourceFolder: $(Build.SourcesDirectory)/bin/.pio/build/nodemcuv2/
          Contents: 'firmware.bin'
          TargetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          ArtifactName: 'Firmware $(Build.BuildNumber)'
          PathtoPublish: $(Build.ArtifactStagingDirectory)
          publishLocation: Container
          TargetPath: .