on: push

jobs:
  esp32-platformio:
    container: infinitecoding/platformio-for-ci:latest
    runs-on: ubuntu-18.04
    steps:
      - run: |
          rm -fdr bin
          mkdir bin
        name: 'Prepare output directories'      
      - run: platformio ci --build-dir="./bin" --keep-build-dir --project-conf=platformio.ini ./src/
        name: 'Build firmware'
      - uses: CopyFiles@2
        inputs:
          SourceFolder: $(Build.SourcesDirectory)/bin/.pio/build/nodemcuv2/
          Contents: 'firmware.bin'
          TargetFolder: $(Build.ArtifactStagingDirectory)
      - uses: PublishBuildArtifacts@1
        inputs:
          ArtifactName: 'Firmware $(Build.BuildNumber)'
          PathtoPublish: $(Build.ArtifactStagingDirectory)
          publishLocation: Container
          TargetPath: .